version: '3'

services:
  api:
    build: .
    command: bundle exec rails server
    depends_on:
    - db
    environment:
      PGDBNAME: mini_investor_api_rb
      PGHOST: db
      PGPORT: '5432'
      PGUSER: postgres
      RAILS_ENV: development
    ports:
    - '4000:3000'
    volumes:
    - .:/app
  db:
    image: postgres:11.1-alpine
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
    - '5431:5432'

  web:
    image: baruh/mini-investor-ui
    ports:
    - '8080:80'
    depends_on:
    - api
volumes:
  pgdata:
